resources:
- name: go-url-preview
  type: git    
  source: &github-secrets
    branch: master
    uri: http://github.com/emc-dojo/go-url-preview
    username: {{github_user}}
    password: {{github_password}}
    skip_ssl_verification: true

- name: go-url-preview-version
  type: semver
  source:
    <<: *github-secrets
    driver: git
    file: ci/version

jobs:
- name: ginkgo-unit
  serial: true
  plan:
  - aggregate:
    - get: go-url-preview
      trigger: true
  - task: ginkgo-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: emcdojo/gourlpreview
      run:
        path: go-url-preview/ci/tasks/ginkgo.sh
      inputs:
      - name: go-url-preview

- name: push-to-test-cf
  serial: true
  plan:
  - aggregate:
    - get: go-url-preview
      trigger: true
      passed: [ginkgo-unit]
  - task: push-to-test-cf
    docker-image: &cf-docker
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          insecure_registries: [{{docker_registry}}]
    config:
      <<: *cf-docker
      inputs:
      - name: go-url-preview
      run:
        path: go-url-preview/ci/tasks/push-to-test-cf.sh
      params:
        CF_ENDPOINT:              {{cf_test_endpoint}}
        CF_USERNAME:              {{cf_test_username}}
        CF_PASSWORD:              {{cf_test_password}}
        CF_ORG:                   {{cf_test_org}}
        CF_SPACE:                 {{cf_test_space}}


- name: push-to-cf
  serial: true
  plan:
  - aggregate:
    - get: go-url-preview
      trigger: false
      passed: [push-to-test-cf]
  - task: push-to-cf
    config:
      <<: *cf-docker
      inputs:
      - name: go-url-preview
      run:
        path: go-url-preview/ci/tasks/push-to-cf.sh
      params:
        CF_ENDPOINT:              {{cf_test_endpoint}}
        CF_USERNAME:              {{cf_test_username}}
        CF_PASSWORD:              {{cf_test_password}}
        CF_ORG:                   {{cf_test_org}}
        CF_SPACE:                 {{cf_test_space}}

- name: promote
  serial: true
  plan:
  - aggregate:
    - get: go-url-preview
      passed:
      - push-to-test-cf
      trigger: true
    - get: go-url-preview-version
      params:
        bump: major
  - task: promote
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: emcdojo/gourlpreview
      params:
        GITHUB_EMAIL: {{github_email}}
        GITHUB_USER:  {{github_user}}
      run:
        path: go-url-preview/ci/tasks/promote-candidate.sh
      inputs:
      - name: go-url-preview
      - name: go-url-preview-version
      outputs:
      - name: promote
  - put: go-url-preview
    params:
      rebase: true
      repository: promote/go-url-preview
      tag: promote/integer_version
      tag_prefix: v
